# Generated by Django 5.0.1 on 2024-03-04 05:13

import chatbox.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_new_user_new_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order',
            name='user',
            field=models.ForeignKey(default=chatbox.models.new_user, on_delete=django.db.models.deletion.CASCADE, to='chatbox.new_user'),
        ),
    ]
