# Generated by Django 5.0.1 on 2024-03-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0006_remove_new_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chatbox.new_user'),
        ),
    ]
